### ISSUE TITLE
Error en name al exportar archivos .shp

### ISSUE THREAD

**Issue by marlucjo** [IngenieroGeomatico/QGIS2API-CNIG#3]
Cuando se utiliza el plugin con archivos .shp, el archivo index.html generado arroja un error porque incorpora comillas y paréntesis en exceso.  Se muestran imágenes antes y después de modificar un fichero .html de ejemplo.
 
![img1](https://github.com/IngenieroGeomatico/QGIS2API-CNIG/assets/12729712/e2aa50d0-6950-4e07-bc67-bf837d7e94bb)
![img2](https://github.com/IngenieroGeomatico/QGIS2API-CNIG/assets/12729712/07a2b568-955a-4f00-805e-48b846a619a6)

**Comment by IngenieroGeomatico** [comment]
Buenas:

Muchas gracias por avisar del problema. En la subida de código de este commit: https://github.com/IngenieroGeomatico/QGIS2API-CNIG/commit/f432c8e934f8f4a41f6c6b13d18649445eeb5af2#diff-9b9c7127b1256089a4c0b70528bee90f3f62e7f05b1aa93ee7200b01f7929eb9R757   ha quedado resuelto el problema.

Para la próxima versión que libere del plugin, estará resuelto.
